# [参考]
# https://dev.classmethod.jp/articles/eslint-configurations-2020/

plugins:
  - vue

extends:
  - plugin:vue/recommended

rules:
    # 不要なカッコは消す
    no-extra-parens : 1
    # 無駄なスペースは削除
    no-multi-spaces: 2
    # 不要な空白行は削除。2行開けてたらエラー
    no-multiple-empty-lines: [2, {"max": 1}]
    # 関数とカッコはあけない(function hoge() {/** */})
    func-call-spacing: [2, "never"]
    # セミコロンは禁止
    semi: [2, "never"]
    # 文字列はシングルクオートのみ
    quotes: [2, "single"]
    # varは禁止
    no-var: 2
    # jsのインデントは２
    indent: [2, 2]
    # かっこの中はスペースなし！違和感
    space-in-parens: [2, "never"]
    # カンマの前後にスペース入れる？
    comma-spacing: 2
    # 配列のindexには空白入れるな(hogehoge[ x ])
    computed-property-spacing: 2
    # キー
    key-spacing: 2
    # キーワードの前後には適切なスペースを
    keyword-spacing: 2
